export interface Player {
  Rank: number;
  PlayerName: string;
  Team: string;
  Position: string;
}

export const playerRankings: Player[] = [
  {
    Rank: 1,
    PlayerName: "Justin Jefferson",
    Team: "MIN",
    Position: "WR",
  },
  {
    Rank: 2,
    PlayerName: "Ja'Marr Chase",
    Team: "CIN",
    Position: "WR",
  },
  {
    Rank: 3,
    PlayerName: "Christian McCaffrey",
    Team: "SF",
    Position: "RB",
  },
  {
    Rank: 4,
    PlayerName: "Tyreek Hill",
    Team: "MIA",
    Position: "WR",
  },
  {
    Rank: 5,
    PlayerName: "Austin Ekeler",
    Team: "WAS",
    Position: "RB",
  },
  {
    Rank: 6,
    PlayerName: "Nick Chubb",
    Team: "CLE",
    Position: "RB",
  },
  {
    Rank: 7,
    PlayerName: "Stefon Diggs",
    Team: "HOU",
    Position: "WR",
  },
  {
    Rank: 8,
    PlayerName: "Bijan Robinson",
    Team: "ATL",
    Position: "RB",
  },
  {
    Rank: 9,
    PlayerName: "Garrett Wilson",
    Team: "NYJ",
    Position: "WR",
  },
  {
    Rank: 10,
    PlayerName: "A.J. Brown",
    Team: "PHI",
    Position: "WR",
  },
  {
    Rank: 11,
    PlayerName: "Saquon Barkley",
    Team: "PHI",
    Position: "RB",
  },
  {
    Rank: 12,
    PlayerName: "Tony Pollard",
    Team: "TEN",
    Position: "RB",
  },
  {
    Rank: 13,
    PlayerName: "CeeDee Lamb",
    Team: "DAL",
    Position: "WR",
  },
  {
    Rank: 14,
    PlayerName: "Amon-Ra St. Brown",
    Team: "DET",
    Position: "WR",
  },
  {
    Rank: 15,
    PlayerName: "Davante Adams",
    Team: "LV",
    Position: "WR",
  },
  {
    Rank: 16,
    PlayerName: "Derrick Henry",
    Team: "BAL",
    Position: "RB",
  },
  {
    Rank: 17,
    PlayerName: "Travis Kelce",
    Team: "KC",
    Position: "TE",
  },
  {
    Rank: 18,
    PlayerName: "Josh Jacobs",
    Team: "GB",
    Position: "RB",
  },
  {
    Rank: 19,
    PlayerName: "Chris Olave",
    Team: "NO",
    Position: "WR",
  },
  {
    Rank: 20,
    PlayerName: "Jaylen Waddle",
    Team: "MIA",
    Position: "WR",
  },
  {
    Rank: 21,
    PlayerName: "DeVonta Smith",
    Team: "PHI",
    Position: "WR",
  },
  {
    Rank: 22,
    PlayerName: "Calvin Ridley",
    Team: "TEN",
    Position: "WR",
  },
  {
    Rank: 23,
    PlayerName: "Tee Higgins",
    Team: "CIN",
    Position: "WR",
  },
  {
    Rank: 24,
    PlayerName: "Travis Etienne Jr.",
    Team: "JAC",
    Position: "RB",
  },
  {
    Rank: 25,
    PlayerName: "Jalen Hurts",
    Team: "PHI",
    Position: "QB",
  },
  {
    Rank: 26,
    PlayerName: "Joe Mixon",
    Team: "HOU",
    Position: "RB",
  },
  {
    Rank: 27,
    PlayerName: "DK Metcalf",
    Team: "SEA",
    Position: "WR",
  },
  {
    Rank: 28,
    PlayerName: "Patrick Mahomes II",
    Team: "KC",
    Position: "QB",
  },
  {
    Rank: 29,
    PlayerName: "Najee Harris",
    Team: "PIT",
    Position: "RB",
  },
  {
    Rank: 30,
    PlayerName: "Rhamondre Stevenson",
    Team: "NE",
    Position: "RB",
  },
  {
    Rank: 31,
    PlayerName: "Aaron Jones",
    Team: "MIN",
    Position: "RB",
  },
  {
    Rank: 32,
    PlayerName: "Josh Allen",
    Team: "BUF",
    Position: "QB",
  },
  {
    Rank: 33,
    PlayerName: "Jahmyr Gibbs",
    Team: "DET",
    Position: "RB",
  },
  {
    Rank: 34,
    PlayerName: "Amari Cooper",
    Team: "CLE",
    Position: "WR",
  },
  {
    Rank: 35,
    PlayerName: "Dameon Pierce",
    Team: "HOU",
    Position: "RB",
  },
  {
    Rank: 36,
    PlayerName: "Mark Andrews",
    Team: "BAL",
    Position: "TE",
  },
  {
    Rank: 37,
    PlayerName: "J.K. Dobbins",
    Team: "LAC",
    Position: "RB",
  },
  {
    Rank: 38,
    PlayerName: "Deebo Samuel Sr.",
    Team: "SF",
    Position: "WR",
  },
  {
    Rank: 39,
    PlayerName: "Kenneth Walker III",
    Team: "SEA",
    Position: "RB",
  },
  {
    Rank: 40,
    PlayerName: "Cooper Kupp",
    Team: "LAR",
    Position: "WR",
  },
  {
    Rank: 41,
    PlayerName: "Miles Sanders",
    Team: "CAR",
    Position: "RB",
  },
  {
    Rank: 42,
    PlayerName: "Lamar Jackson",
    Team: "BAL",
    Position: "QB",
  },
  {
    Rank: 43,
    PlayerName: "Drake London",
    Team: "ATL",
    Position: "WR",
  },
  {
    Rank: 44,
    PlayerName: "Breece Hall",
    Team: "NYJ",
    Position: "RB",
  },
  {
    Rank: 45,
    PlayerName: "Keenan Allen",
    Team: "CHI",
    Position: "WR",
  },
  {
    Rank: 46,
    PlayerName: "Alexander Mattison",
    Team: "LV",
    Position: "RB",
  },
  {
    Rank: 47,
    PlayerName: "James Cook",
    Team: "BUF",
    Position: "RB",
  },
  {
    Rank: 48,
    PlayerName: "Tyler Lockett",
    Team: "SEA",
    Position: "WR",
  },
  {
    Rank: 49,
    PlayerName: "Brandon Aiyuk",
    Team: "SF",
    Position: "WR",
  },
  {
    Rank: 50,
    PlayerName: "Diontae Johnson",
    Team: "CAR",
    Position: "WR",
  },
  {
    Rank: 51,
    PlayerName: "Cam Akers",
    Team: "HOU",
    Position: "RB",
  },
  {
    Rank: 52,
    PlayerName: "Darren Waller",
    Team: "FA",
    Position: "TE",
  },
  {
    Rank: 53,
    PlayerName: "DJ Moore",
    Team: "CHI",
    Position: "WR",
  },
  {
    Rank: 54,
    PlayerName: "Terry McLaurin",
    Team: "WAS",
    Position: "WR",
  },
  {
    Rank: 55,
    PlayerName: "T.J. Hockenson",
    Team: "MIN",
    Position: "TE",
  },
  {
    Rank: 56,
    PlayerName: "DeAndre Hopkins",
    Team: "TEN",
    Position: "WR",
  },
  {
    Rank: 57,
    PlayerName: "Justin Fields",
    Team: "PIT",
    Position: "QB",
  },
  {
    Rank: 58,
    PlayerName: "David Montgomery",
    Team: "DET",
    Position: "RB",
  },
  {
    Rank: 59,
    PlayerName: "Joe Burrow",
    Team: "CIN",
    Position: "QB",
  },
  {
    Rank: 60,
    PlayerName: "James Conner",
    Team: "ARI",
    Position: "RB",
  },
  {
    Rank: 61,
    PlayerName: "Jonathan Taylor",
    Team: "IND",
    Position: "RB",
  },
  {
    Rank: 62,
    PlayerName: "Chris Godwin",
    Team: "TB",
    Position: "WR",
  },
  {
    Rank: 63,
    PlayerName: "Jahan Dotson",
    Team: "WAS",
    Position: "WR",
  },
  {
    Rank: 64,
    PlayerName: "George Kittle",
    Team: "SF",
    Position: "TE",
  },
  {
    Rank: 65,
    PlayerName: "Christian Watson",
    Team: "GB",
    Position: "WR",
  },
  {
    Rank: 66,
    PlayerName: "Khalil Herbert",
    Team: "CHI",
    Position: "RB",
  },
  {
    Rank: 67,
    PlayerName: "Trevor Lawrence",
    Team: "JAC",
    Position: "QB",
  },
  {
    Rank: 68,
    PlayerName: "Mike Evans",
    Team: "TB",
    Position: "WR",
  },
  {
    Rank: 69,
    PlayerName: "Rachaad White",
    Team: "TB",
    Position: "RB",
  },
  {
    Rank: 70,
    PlayerName: "Michael Pittman Jr.",
    Team: "IND",
    Position: "WR",
  },
  {
    Rank: 71,
    PlayerName: "George Pickens",
    Team: "PIT",
    Position: "WR",
  },
  {
    Rank: 72,
    PlayerName: "Christian Kirk",
    Team: "JAC",
    Position: "WR",
  },
  {
    Rank: 73,
    PlayerName: "Mike Williams",
    Team: "NYJ",
    Position: "WR",
  },
  {
    Rank: 74,
    PlayerName: "Dalvin Cook",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 75,
    PlayerName: "Kyle Pitts",
    Team: "ATL",
    Position: "TE",
  },
  {
    Rank: 76,
    PlayerName: "Javonte Williams",
    Team: "DEN",
    Position: "RB",
  },
  {
    Rank: 77,
    PlayerName: "Justin Herbert",
    Team: "LAC",
    Position: "QB",
  },
  {
    Rank: 78,
    PlayerName: "Dallas Goedert",
    Team: "PHI",
    Position: "TE",
  },
  {
    Rank: 79,
    PlayerName: "Isiah Pacheco",
    Team: "KC",
    Position: "RB",
  },
  {
    Rank: 80,
    PlayerName: "Hollywood Brown",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 81,
    PlayerName: "Alvin Kamara",
    Team: "NO",
    Position: "RB",
  },
  {
    Rank: 82,
    PlayerName: "Jerry Jeudy",
    Team: "CLE",
    Position: "WR",
  },
  {
    Rank: 83,
    PlayerName: "Brian Robinson Jr.",
    Team: "WAS",
    Position: "RB",
  },
  {
    Rank: 84,
    PlayerName: "D'Andre Swift",
    Team: "CHI",
    Position: "RB",
  },
  {
    Rank: 85,
    PlayerName: "Gabe Davis",
    Team: "JAC",
    Position: "WR",
  },
  {
    Rank: 86,
    PlayerName: "AJ Dillon",
    Team: "GB",
    Position: "RB",
  },
  {
    Rank: 87,
    PlayerName: "Pat Freiermuth",
    Team: "PIT",
    Position: "TE",
  },
  {
    Rank: 88,
    PlayerName: "Jaxon Smith-Njigba",
    Team: "SEA",
    Position: "WR",
  },
  {
    Rank: 89,
    PlayerName: "Dak Prescott",
    Team: "DAL",
    Position: "QB",
  },
  {
    Rank: 90,
    PlayerName: "Daniel Jones",
    Team: "NYG",
    Position: "QB",
  },
  {
    Rank: 91,
    PlayerName: "Antonio Gibson",
    Team: "NE",
    Position: "RB",
  },
  {
    Rank: 92,
    PlayerName: "Evan Engram",
    Team: "JAC",
    Position: "TE",
  },
  {
    Rank: 93,
    PlayerName: "Jordan Addison",
    Team: "MIN",
    Position: "WR",
  },
  {
    Rank: 94,
    PlayerName: "Samaje Perine",
    Team: "DEN",
    Position: "RB",
  },
  {
    Rank: 95,
    PlayerName: "Jamaal Williams",
    Team: "NO",
    Position: "RB",
  },
  {
    Rank: 96,
    PlayerName: "Zach Charbonnet",
    Team: "SEA",
    Position: "RB",
  },
  {
    Rank: 97,
    PlayerName: "Raheem Mostert",
    Team: "MIA",
    Position: "RB",
  },
  {
    Rank: 98,
    PlayerName: "Geno Smith",
    Team: "SEA",
    Position: "QB",
  },
  {
    Rank: 99,
    PlayerName: "Jerick McKinnon",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 100,
    PlayerName: "Tua Tagovailoa",
    Team: "MIA",
    Position: "QB",
  },
  {
    Rank: 101,
    PlayerName: "Deshaun Watson",
    Team: "CLE",
    Position: "QB",
  },
  {
    Rank: 102,
    PlayerName: "Elijah Moore",
    Team: "CLE",
    Position: "WR",
  },
  {
    Rank: 103,
    PlayerName: "Rashod Bateman",
    Team: "BAL",
    Position: "WR",
  },
  {
    Rank: 104,
    PlayerName: "Courtland Sutton",
    Team: "DEN",
    Position: "WR",
  },
  {
    Rank: 105,
    PlayerName: "Treylon Burks",
    Team: "TEN",
    Position: "WR",
  },
  {
    Rank: 106,
    PlayerName: "Nico Collins",
    Team: "HOU",
    Position: "WR",
  },
  {
    Rank: 107,
    PlayerName: "Brandin Cooks",
    Team: "DAL",
    Position: "WR",
  },
  {
    Rank: 108,
    PlayerName: "David Njoku",
    Team: "CLE",
    Position: "TE",
  },
  {
    Rank: 109,
    PlayerName: "Skyy Moore",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 110,
    PlayerName: "Anthony Richardson",
    Team: "IND",
    Position: "QB",
  },
  {
    Rank: 111,
    PlayerName: "Jaylen Warren",
    Team: "PIT",
    Position: "RB",
  },
  {
    Rank: 112,
    PlayerName: "Kirk Cousins",
    Team: "ATL",
    Position: "QB",
  },
  {
    Rank: 113,
    PlayerName: "Rashaad Penny",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 114,
    PlayerName: "Sam LaPorta",
    Team: "DET",
    Position: "TE",
  },
  {
    Rank: 115,
    PlayerName: "Tyler Higbee",
    Team: "LAR",
    Position: "TE",
  },
  {
    Rank: 116,
    PlayerName: "Aaron Rodgers",
    Team: "NYJ",
    Position: "QB",
  },
  {
    Rank: 117,
    PlayerName: "JuJu Smith-Schuster",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 118,
    PlayerName: "Tyler Allgeier",
    Team: "ATL",
    Position: "RB",
  },
  {
    Rank: 119,
    PlayerName: "Jakobi Meyers",
    Team: "LV",
    Position: "WR",
  },
  {
    Rank: 120,
    PlayerName: "Michael Thomas",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 121,
    PlayerName: "Dalton Kincaid",
    Team: "BUF",
    Position: "TE",
  },
  {
    Rank: 122,
    PlayerName: "Zay Flowers",
    Team: "BAL",
    Position: "WR",
  },
  {
    Rank: 123,
    PlayerName: "Chigoziem Okonkwo",
    Team: "TEN",
    Position: "TE",
  },
  {
    Rank: 124,
    PlayerName: "Ezekiel Elliott",
    Team: "DAL",
    Position: "RB",
  },
  {
    Rank: 125,
    PlayerName: "Damien Harris",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 126,
    PlayerName: "Kenneth Gainwell",
    Team: "PHI",
    Position: "RB",
  },
  {
    Rank: 127,
    PlayerName: "Tank Bigsby",
    Team: "JAC",
    Position: "RB",
  },
  {
    Rank: 128,
    PlayerName: "Elijah Mitchell",
    Team: "SF",
    Position: "RB",
  },
  {
    Rank: 129,
    PlayerName: "Marvin Mims Jr.",
    Team: "DEN",
    Position: "WR",
  },
  {
    Rank: 130,
    PlayerName: "Adam Thielen",
    Team: "CAR",
    Position: "WR",
  },
  {
    Rank: 131,
    PlayerName: "De'Von Achane",
    Team: "MIA",
    Position: "RB",
  },
  {
    Rank: 132,
    PlayerName: "Odell Beckham Jr.",
    Team: "MIA",
    Position: "WR",
  },
  {
    Rank: 133,
    PlayerName: "Quentin Johnston",
    Team: "LAC",
    Position: "WR",
  },
  {
    Rank: 134,
    PlayerName: "Juwan Johnson",
    Team: "NO",
    Position: "TE",
  },
  {
    Rank: 135,
    PlayerName: "Van Jefferson",
    Team: "PIT",
    Position: "WR",
  },
  {
    Rank: 136,
    PlayerName: "Tyler Boyd",
    Team: "TEN",
    Position: "WR",
  },
  {
    Rank: 137,
    PlayerName: "Romeo Doubs",
    Team: "GB",
    Position: "WR",
  },
  {
    Rank: 138,
    PlayerName: "Cole Kmet",
    Team: "CHI",
    Position: "TE",
  },
  {
    Rank: 139,
    PlayerName: "Jared Goff",
    Team: "DET",
    Position: "QB",
  },
  {
    Rank: 140,
    PlayerName: "Kadarius Toney",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 141,
    PlayerName: "Brock Purdy",
    Team: "SF",
    Position: "QB",
  },
  {
    Rank: 142,
    PlayerName: "Allen Lazard",
    Team: "NYJ",
    Position: "WR",
  },
  {
    Rank: 143,
    PlayerName: "Michael Gallup",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 144,
    PlayerName: "Dalton Schultz",
    Team: "HOU",
    Position: "TE",
  },
  {
    Rank: 145,
    PlayerName: "Jake Ferguson",
    Team: "DAL",
    Position: "TE",
  },
  {
    Rank: 146,
    PlayerName: "Darnell Mooney",
    Team: "ATL",
    Position: "WR",
  },
  {
    Rank: 147,
    PlayerName: "San Francisco 49ers",
    Team: "SF",
    Position: "DST",
  },
  {
    Rank: 148,
    PlayerName: "Sam Howell",
    Team: "SEA",
    Position: "QB",
  },
  {
    Rank: 149,
    PlayerName: "Curtis Samuel",
    Team: "BUF",
    Position: "WR",
  },
  {
    Rank: 150,
    PlayerName: "Dallas Cowboys",
    Team: "DAL",
    Position: "DST",
  },
  {
    Rank: 151,
    PlayerName: "Kendre Miller",
    Team: "NO",
    Position: "RB",
  },
  {
    Rank: 152,
    PlayerName: "Greg Dulcich",
    Team: "DEN",
    Position: "TE",
  },
  {
    Rank: 153,
    PlayerName: "Philadelphia Eagles",
    Team: "PHI",
    Position: "DST",
  },
  {
    Rank: 154,
    PlayerName: "Zay Jones",
    Team: "ARI",
    Position: "WR",
  },
  {
    Rank: 155,
    PlayerName: "Tyjae Spears",
    Team: "TEN",
    Position: "RB",
  },
  {
    Rank: 156,
    PlayerName: "Hunter Henry",
    Team: "NE",
    Position: "TE",
  },
  {
    Rank: 157,
    PlayerName: "Gerald Everett",
    Team: "CHI",
    Position: "TE",
  },
  {
    Rank: 158,
    PlayerName: "Buffalo Bills",
    Team: "BUF",
    Position: "DST",
  },
  {
    Rank: 159,
    PlayerName: "Russell Wilson",
    Team: "PIT",
    Position: "QB",
  },
  {
    Rank: 160,
    PlayerName: "Jonathan Mingo",
    Team: "CAR",
    Position: "WR",
  },
  {
    Rank: 161,
    PlayerName: "Devin Singletary",
    Team: "NYG",
    Position: "RB",
  },
  {
    Rank: 162,
    PlayerName: "Jayden Reed",
    Team: "GB",
    Position: "WR",
  },
  {
    Rank: 163,
    PlayerName: "New York Jets",
    Team: "NYJ",
    Position: "DST",
  },
  {
    Rank: 164,
    PlayerName: "Gus Edwards",
    Team: "LAC",
    Position: "RB",
  },
  {
    Rank: 165,
    PlayerName: "Justin Tucker",
    Team: "BAL",
    Position: "K",
  },
  {
    Rank: 166,
    PlayerName: "Denver Broncos",
    Team: "DEN",
    Position: "DST",
  },
  {
    Rank: 167,
    PlayerName: "Rashid Shaheed",
    Team: "NO",
    Position: "WR",
  },
  {
    Rank: 168,
    PlayerName: "New Orleans Saints",
    Team: "NO",
    Position: "DST",
  },
  {
    Rank: 169,
    PlayerName: "Alec Pierce",
    Team: "IND",
    Position: "WR",
  },
  {
    Rank: 170,
    PlayerName: "Kenny Pickett",
    Team: "PHI",
    Position: "QB",
  },
  {
    Rank: 171,
    PlayerName: "Roschon Johnson",
    Team: "CHI",
    Position: "RB",
  },
  {
    Rank: 172,
    PlayerName: "Jerome Ford",
    Team: "CLE",
    Position: "RB",
  },
  {
    Rank: 173,
    PlayerName: "Derek Carr",
    Team: "NO",
    Position: "QB",
  },
  {
    Rank: 174,
    PlayerName: "Jameson Williams",
    Team: "DET",
    Position: "WR",
  },
  {
    Rank: 175,
    PlayerName: "Irv Smith Jr.",
    Team: "KC",
    Position: "TE",
  },
  {
    Rank: 176,
    PlayerName: "D'Onta Foreman",
    Team: "CLE",
    Position: "RB",
  },
  {
    Rank: 177,
    PlayerName: "New England Patriots",
    Team: "NE",
    Position: "DST",
  },
  {
    Rank: 178,
    PlayerName: "Jalin Hyatt",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 179,
    PlayerName: "Daniel Carlson",
    Team: "LV",
    Position: "K",
  },
  {
    Rank: 180,
    PlayerName: "Rondale Moore",
    Team: "ATL",
    Position: "WR",
  },
  {
    Rank: 181,
    PlayerName: "Donovan Peoples-Jones",
    Team: "DET",
    Position: "WR",
  },
  {
    Rank: 182,
    PlayerName: "Isaiah Hodgins",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 183,
    PlayerName: "Matthew Stafford",
    Team: "LAR",
    Position: "QB",
  },
  {
    Rank: 184,
    PlayerName: "Baltimore Ravens",
    Team: "BAL",
    Position: "DST",
  },
  {
    Rank: 185,
    PlayerName: "Younghoe Koo",
    Team: "ATL",
    Position: "K",
  },
  {
    Rank: 186,
    PlayerName: "Luke Musgrave",
    Team: "GB",
    Position: "TE",
  },
  {
    Rank: 187,
    PlayerName: "Jordan Love",
    Team: "GB",
    Position: "QB",
  },
  {
    Rank: 188,
    PlayerName: "Zack Moss",
    Team: "CIN",
    Position: "RB",
  },
  {
    Rank: 189,
    PlayerName: "DJ Chark Jr.",
    Team: "LAC",
    Position: "WR",
  },
  {
    Rank: 190,
    PlayerName: "Tyler Bass",
    Team: "BUF",
    Position: "K",
  },
  {
    Rank: 191,
    PlayerName: "K.J. Osborn",
    Team: "NE",
    Position: "WR",
  },
  {
    Rank: 192,
    PlayerName: "Pittsburgh Steelers",
    Team: "PIT",
    Position: "DST",
  },
  {
    Rank: 193,
    PlayerName: "Sean Tucker",
    Team: "TB",
    Position: "RB",
  },
  {
    Rank: 194,
    PlayerName: "Marquez Valdes-Scantling",
    Team: "BUF",
    Position: "WR",
  },
  {
    Rank: 195,
    PlayerName: "Evan McPherson",
    Team: "CIN",
    Position: "K",
  },
  {
    Rank: 196,
    PlayerName: "Clyde Edwards-Helaire",
    Team: "KC",
    Position: "RB",
  },
  {
    Rank: 197,
    PlayerName: "Miami Dolphins",
    Team: "MIA",
    Position: "DST",
  },
  {
    Rank: 198,
    PlayerName: "Joshua Palmer",
    Team: "LAC",
    Position: "WR",
  },
  {
    Rank: 199,
    PlayerName: "Rashee Rice",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 200,
    PlayerName: "Hayden Hurst",
    Team: "LAC",
    Position: "TE",
  },
  {
    Rank: 201,
    PlayerName: "Chuba Hubbard",
    Team: "CAR",
    Position: "RB",
  },
  {
    Rank: 202,
    PlayerName: "Jeff Wilson Jr.",
    Team: "MIA",
    Position: "RB",
  },
  {
    Rank: 203,
    PlayerName: "Harrison Butker",
    Team: "KC",
    Position: "K",
  },
  {
    Rank: 204,
    PlayerName: "Cincinnati Bengals",
    Team: "CIN",
    Position: "DST",
  },
  {
    Rank: 205,
    PlayerName: "Joshua Kelley",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 206,
    PlayerName: "Ty Chandler",
    Team: "MIN",
    Position: "RB",
  },
  {
    Rank: 207,
    PlayerName: "Zamir White",
    Team: "LV",
    Position: "RB",
  },
  {
    Rank: 208,
    PlayerName: "Trey McBride",
    Team: "ARI",
    Position: "TE",
  },
  {
    Rank: 209,
    PlayerName: "Kansas City Chiefs",
    Team: "KC",
    Position: "DST",
  },
  {
    Rank: 210,
    PlayerName: "Darius Slayton",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 211,
    PlayerName: "Evan Hull",
    Team: "IND",
    Position: "RB",
  },
  {
    Rank: 212,
    PlayerName: "Deon Jackson",
    Team: "NYJ",
    Position: "RB",
  },
  {
    Rank: 213,
    PlayerName: "Ryan Tannehill",
    Team: "FA",
    Position: "QB",
  },
  {
    Rank: 214,
    PlayerName: "Keaontay Ingram",
    Team: "KC",
    Position: "RB",
  },
  {
    Rank: 215,
    PlayerName: "Cade Otton",
    Team: "TB",
    Position: "TE",
  },
  {
    Rank: 216,
    PlayerName: "Bryce Young",
    Team: "CAR",
    Position: "QB",
  },
  {
    Rank: 217,
    PlayerName: "Puka Nacua",
    Team: "LAR",
    Position: "WR",
  },
  {
    Rank: 218,
    PlayerName: "Washington Commanders",
    Team: "WAS",
    Position: "DST",
  },
  {
    Rank: 219,
    PlayerName: "Cleveland Browns",
    Team: "CLE",
    Position: "DST",
  },
  {
    Rank: 220,
    PlayerName: "Brandon McManus",
    Team: "FA",
    Position: "K",
  },
  {
    Rank: 221,
    PlayerName: "DeVante Parker",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 222,
    PlayerName: "Los Angeles Chargers",
    Team: "LAC",
    Position: "DST",
  },
  {
    Rank: 223,
    PlayerName: "Jason Sanders",
    Team: "MIA",
    Position: "K",
  },
  {
    Rank: 224,
    PlayerName: "Cameron Dicker",
    Team: "LAC",
    Position: "K",
  },
  {
    Rank: 225,
    PlayerName: "Kyren Williams",
    Team: "LAR",
    Position: "RB",
  },
  {
    Rank: 226,
    PlayerName: "Jake Elliott",
    Team: "PHI",
    Position: "K",
  },
  {
    Rank: 227,
    PlayerName: "Jason Myers",
    Team: "SEA",
    Position: "K",
  },
  {
    Rank: 228,
    PlayerName: "Dawson Knox",
    Team: "BUF",
    Position: "TE",
  },
  {
    Rank: 229,
    PlayerName: "Green Bay Packers",
    Team: "GB",
    Position: "DST",
  },
  {
    Rank: 230,
    PlayerName: "Michael Mayer",
    Team: "LV",
    Position: "TE",
  },
  {
    Rank: 231,
    PlayerName: "Taysom Hill",
    Team: "NO",
    Position: "TE",
  },
  {
    Rank: 232,
    PlayerName: "Jacksonville Jaguars",
    Team: "JAC",
    Position: "DST",
  },
  {
    Rank: 233,
    PlayerName: "Robert Woods",
    Team: "HOU",
    Position: "WR",
  },
  {
    Rank: 234,
    PlayerName: "Mike Gesicki",
    Team: "CIN",
    Position: "TE",
  },
  {
    Rank: 235,
    PlayerName: "Greg Joseph",
    Team: "GB",
    Position: "K",
  },
  {
    Rank: 236,
    PlayerName: "Allen Robinson II",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 237,
    PlayerName: "Michael Wilson",
    Team: "ARI",
    Position: "WR",
  },
  {
    Rank: 238,
    PlayerName: "John Metchie III",
    Team: "HOU",
    Position: "WR",
  },
  {
    Rank: 239,
    PlayerName: "Terrace Marshall Jr.",
    Team: "CAR",
    Position: "WR",
  },
  {
    Rank: 240,
    PlayerName: "Logan Thomas",
    Team: "FA",
    Position: "TE",
  },
  {
    Rank: 241,
    PlayerName: "Tampa Bay Buccaneers",
    Team: "TB",
    Position: "DST",
  },
  {
    Rank: 242,
    PlayerName: "Wan'Dale Robinson",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 243,
    PlayerName: "Tyler Conklin",
    Team: "NYJ",
    Position: "TE",
  },
  {
    Rank: 244,
    PlayerName: "Noah Fant",
    Team: "SEA",
    Position: "TE",
  },
  {
    Rank: 245,
    PlayerName: "Cordarrelle Patterson",
    Team: "PIT",
    Position: "RB",
  },
  {
    Rank: 246,
    PlayerName: "Chase Claypool",
    Team: "BUF",
    Position: "WR",
  },
  {
    Rank: 247,
    PlayerName: "Sterling Shepard",
    Team: "TB",
    Position: "WR",
  },
  {
    Rank: 248,
    PlayerName: "Graham Gano",
    Team: "NYG",
    Position: "K",
  },
  {
    Rank: 249,
    PlayerName: "Josh Downs",
    Team: "IND",
    Position: "WR",
  },
  {
    Rank: 250,
    PlayerName: "Hunter Renfrow",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 251,
    PlayerName: "Jimmy Garoppolo",
    Team: "LAR",
    Position: "QB",
  },
  {
    Rank: 252,
    PlayerName: "Baker Mayfield",
    Team: "TB",
    Position: "QB",
  },
  {
    Rank: 253,
    PlayerName: "Pierre Strong Jr.",
    Team: "CLE",
    Position: "RB",
  },
  {
    Rank: 254,
    PlayerName: "Parris Campbell",
    Team: "PHI",
    Position: "WR",
  },
  {
    Rank: 255,
    PlayerName: "Nick Folk",
    Team: "TEN",
    Position: "K",
  },
  {
    Rank: 256,
    PlayerName: "Kyler Murray",
    Team: "ARI",
    Position: "QB",
  },
  {
    Rank: 257,
    PlayerName: "Greg Zuerlein",
    Team: "NYJ",
    Position: "K",
  },
  {
    Rank: 258,
    PlayerName: "Riley Patterson",
    Team: "WAS",
    Position: "K",
  },
  {
    Rank: 259,
    PlayerName: "Desmond Ridder",
    Team: "ARI",
    Position: "QB",
  },
  {
    Rank: 260,
    PlayerName: "Seattle Seahawks",
    Team: "SEA",
    Position: "DST",
  },
  {
    Rank: 261,
    PlayerName: "Kareem Hunt",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 262,
    PlayerName: "Jelani Woods",
    Team: "IND",
    Position: "TE",
  },
  {
    Rank: 263,
    PlayerName: "Richie James Jr.",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 264,
    PlayerName: "Deuce Vaughn",
    Team: "DAL",
    Position: "RB",
  },
  {
    Rank: 265,
    PlayerName: "Los Angeles Rams",
    Team: "LAR",
    Position: "DST",
  },
  {
    Rank: 266,
    PlayerName: "Rico Dowdle",
    Team: "DAL",
    Position: "RB",
  },
  {
    Rank: 267,
    PlayerName: "Isaiah Likely",
    Team: "BAL",
    Position: "TE",
  },
  {
    Rank: 268,
    PlayerName: "Matt Gay",
    Team: "IND",
    Position: "K",
  },
  {
    Rank: 269,
    PlayerName: "Carolina Panthers",
    Team: "CAR",
    Position: "DST",
  },
  {
    Rank: 270,
    PlayerName: "Chris Evans",
    Team: "CIN",
    Position: "RB",
  },
  {
    Rank: 271,
    PlayerName: "Atlanta Falcons",
    Team: "ATL",
    Position: "DST",
  },
  {
    Rank: 272,
    PlayerName: "Randall Cobb",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 273,
    PlayerName: "Wil Lutz",
    Team: "DEN",
    Position: "K",
  },
  {
    Rank: 274,
    PlayerName: "Indianapolis Colts",
    Team: "IND",
    Position: "DST",
  },
  {
    Rank: 275,
    PlayerName: "Blake Grupe",
    Team: "NO",
    Position: "K",
  },
  {
    Rank: 276,
    PlayerName: "Zach Ertz",
    Team: "WAS",
    Position: "TE",
  },
  {
    Rank: 277,
    PlayerName: "Khalil Shakir",
    Team: "BUF",
    Position: "WR",
  },
  {
    Rank: 278,
    PlayerName: "Jake Moody",
    Team: "SF",
    Position: "K",
  },
  {
    Rank: 279,
    PlayerName: "Chris Boswell",
    Team: "PIT",
    Position: "K",
  },
  {
    Rank: 280,
    PlayerName: "Chase Brown",
    Team: "CIN",
    Position: "RB",
  },
  {
    Rank: 281,
    PlayerName: "Tank Dell",
    Team: "HOU",
    Position: "WR",
  },
  {
    Rank: 282,
    PlayerName: "Mac Jones",
    Team: "JAC",
    Position: "QB",
  },
  {
    Rank: 283,
    PlayerName: "Leonard Fournette",
    Team: "FA",
    Position: "RB",
  },
  {
    Rank: 284,
    PlayerName: "New York Giants",
    Team: "NYG",
    Position: "DST",
  },
  {
    Rank: 285,
    PlayerName: "Michael Carter",
    Team: "ARI",
    Position: "RB",
  },
  {
    Rank: 286,
    PlayerName: "Tennessee Titans",
    Team: "TEN",
    Position: "DST",
  },
  {
    Rank: 287,
    PlayerName: "Josh Reynolds",
    Team: "DEN",
    Position: "WR",
  },
  {
    Rank: 288,
    PlayerName: "Calvin Austin III",
    Team: "PIT",
    Position: "WR",
  },
  {
    Rank: 289,
    PlayerName: "Chase Edmonds",
    Team: "TB",
    Position: "RB",
  },
  {
    Rank: 290,
    PlayerName: "C.J. Stroud",
    Team: "HOU",
    Position: "QB",
  },
  {
    Rank: 291,
    PlayerName: "Matt Prater",
    Team: "ARI",
    Position: "K",
  },
  {
    Rank: 292,
    PlayerName: "Isaiah McKenzie",
    Team: "NYG",
    Position: "WR",
  },
  {
    Rank: 293,
    PlayerName: "Cairo Santos",
    Team: "CHI",
    Position: "K",
  },
  {
    Rank: 294,
    PlayerName: "Minnesota Vikings",
    Team: "MIN",
    Position: "DST",
  },
  {
    Rank: 295,
    PlayerName: "Eddy Pineiro",
    Team: "CAR",
    Position: "K",
  },
  {
    Rank: 296,
    PlayerName: "Mecole Hardman Jr.",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 297,
    PlayerName: "Isaiah Spiller",
    Team: "LAC",
    Position: "RB",
  },
  {
    Rank: 298,
    PlayerName: "Foster Moreau",
    Team: "NO",
    Position: "TE",
  },
  {
    Rank: 299,
    PlayerName: "Detroit Lions",
    Team: "DET",
    Position: "DST",
  },
  {
    Rank: 300,
    PlayerName: "Mack Hollins",
    Team: "BUF",
    Position: "WR",
  },
  {
    Rank: 301,
    PlayerName: "Brandon Aubrey",
    Team: "DAL",
    Position: "K",
  },
  {
    Rank: 302,
    PlayerName: "Marvin Jones Jr.",
    Team: "FA",
    Position: "WR",
  },
  {
    Rank: 303,
    PlayerName: "Justyn Ross",
    Team: "KC",
    Position: "WR",
  },
  {
    Rank: 304,
    PlayerName: "Joey Slye",
    Team: "NE",
    Position: "K",
  },
  {
    Rank: 305,
    PlayerName: "Chase McLaughlin",
    Team: "TB",
    Position: "K",
  },
  {
    Rank: 306,
    PlayerName: "Eric Gray",
    Team: "NYG",
    Position: "RB",
  },
  {
    Rank: 307,
    PlayerName: "Dustin Hopkins",
    Team: "CLE",
    Position: "K",
  },
  {
    Rank: 308,
    PlayerName: "Arizona Cardinals",
    Team: "ARI",
    Position: "DST",
  },
  {
    Rank: 309,
    PlayerName: "Colt McCoy",
    Team: "FA",
    Position: "QB",
  },
  {
    Rank: 310,
    PlayerName: "Jacoby Brissett",
    Team: "NE",
    Position: "QB",
  },
  {
    Rank: 311,
    PlayerName: "Tutu Atwell",
    Team: "LAR",
    Position: "WR",
  },
  {
    Rank: 312,
    PlayerName: "Gardner Minshew II",
    Team: "LV",
    Position: "QB",
  },
  {
    Rank: 313,
    PlayerName: "Will Levis",
    Team: "TEN",
    Position: "QB",
  },
  {
    Rank: 314,
    PlayerName: "Kyle Trask",
    Team: "TB",
    Position: "QB",
  },
  {
    Rank: 315,
    PlayerName: "Jordan Mason",
    Team: "SF",
    Position: "RB",
  },
  {
    Rank: 316,
    PlayerName: "Ka'imi Fairbairn",
    Team: "HOU",
    Position: "K",
  },
  {
    Rank: 317,
    PlayerName: "JaMycal Hasty",
    Team: "NE",
    Position: "RB",
  },
  {
    Rank: 318,
    PlayerName: "Chad Ryland",
    Team: "NE",
    Position: "K",
  },
];
